spring:
  profle:
    active: dev
  main:
    show-banner: false
  main:
    show-banner: false
  jpa.hibernate.ddl-auto: validate
  thymeleaf:
    cache: false
  jmx.enabled: false
security:
  basic:
    enabled: false
server.tomcat.access_log_enabled: true

---
spring:
    profiles: dev
    datasource:
      url: jdbc:h2:file:${yachosan.h2.datadir:/tmp}/yachosan
    jpa:
      database: H2
---
spring:
    profiles: heroku
    datasource:
      driverClassName: org.postgresql.Driver
    jpa:
      database: POSTGRESQL