spring:
  main:
    show-banner: false
  datasource:
    url: jdbc:h2:file:${yachosan.h2.datadir:/tmp}/yachosan
  main:
    show-banner: false
  jpa.hibernate.ddl-auto: validate
  thymeleaf:
    cache: false
  jmx.enabled: false
security:
  basic:
    enabled: false
server.tomcat.access_log_enabled: true
